### PR TITLE
DOCTYPE :/

### PR DESCRIPTION
**Pull request by Taki21**

### CODE REVIEW

**Comment by Taki21** [comment]
Why can't I directly commit or merge pull requests?

**Comment by MCUnderground** [comment]
Idk

**Comment by MCUnderground** [comment]
Fixed

**Comment by Taki21** [comment]
thx

**Comment by OGSweg** [comment]
Ummm how dis work? -OG

**Comment by applqpak** [comment]
All he did was change it so it ran as HTML 5..

**Comment by Taki21** [comment]
Yup.
HTML5 IS way easier

**Comment by OGSweg** [comment]
Is this like a Chatroom? -OG

**Comment by Taki21** [comment]
Um...We are just giving some thoughts on my weird PR...lol xD

**Comment by OGSweg** [comment]
Okay....

**Comment by applqpak** [comment]
Does anyone here know how to code in XML/PLIST?

**Comment by MCUnderground** [comment]
I think i do XML. Also we should make private gitter room,idk how through :/

**Comment by applqpak** [comment]
Lol

**Pull request merged**
